[package]
name = "file_util_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "file_util_lib"
crate-type = ["cdylib"]

[dependencies]
flate2 = "1.0.28"
pyo3 = "0.19.0"
